In [1]:
# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
# Install required packages
!pip install -q transformers datasets accelerate sentence-transformers

In [4]:
# Import core libraries
import pandas as pd
import numpy as np
import re
import os

In [5]:
# Import PyTorch
import torch
import torch.nn as nn

In [6]:
# Import sklearn utilities
from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import accuracy_score, f1_score, classification_report

In [7]:
# Import Hugging Face tools
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer
)

In [8]:
# Optional display settings for easier dataframe viewing
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 200)

### Load Dataset

In [9]:
# Load dataset from Google Drive
df = pd.read_csv("/content/drive/MyDrive/cfpb_sample_500k.csv")

In [10]:
df.shape

(500000, 4)

In [11]:
# Check column names
df.columns.tolist()

['text', 'target', 'text_clean', 'target_grouped']

In [12]:
# Check required columns
df[["text_clean", "target_grouped"]].head()

,text_clean,target_grouped
0,hi i am submitting this xxxx xxxx this isn t any influence and this is not a third party xxxx has low and unfair credit number for me in their report i have 87complained times the problem has not ...,Credit reporting
1,a federal education loan was fraudulently opened in my name i filed an ftc identity theft report a doe loan forgery discharge application and submitted supporting documents despite this the depart...,Debt collection
2,i am writing to have the following information removed from my credit file the items that i need deleted are going to be attached in a word document i am a victim of identity theft i have multiple...,Credit reporting
3,i want this late payment remove from my account and i never been late with this account i working so hard to pay this monthly and this is not acceptable see the documents attached,Credit card
4,i am disputing several items on my experian credit report that appear to be inaccurate or incomplete the details of the accounts in question are as follows 1 charged off accounts xxxx xxxx xxxx xx...,Credit reporting

In [13]:
# Check missing values in required columns
df[["text_clean", "target_grouped"]].isnull().sum()

text_clean        0
target_grouped    0
dtype: int64

### Create label mapping

In [14]:
# Create label mappings
label2id = {label: i for i, label in enumerate(sorted(df["target_grouped"].unique()))}
id2label = {i: label for label, i in label2id.items()}

In [15]:
# Create numeric label column
df["label"] = df["target_grouped"].map(label2id)

In [16]:
label2id

{'Auto loan': 0,
 'Bank account': 1,
 'Credit card': 2,
 'Credit reporting': 3,
 'Debt collection': 4,
 'Money transfer': 5,
 'Mortgage': 6,
 'Other': 7,
 'Personal loan': 8,
 'Student loan': 9}

In [17]:
id2label

{0: 'Auto loan',
 1: 'Bank account',
 2: 'Credit card',
 3: 'Credit reporting',
 4: 'Debt collection',
 5: 'Money transfer',
 6: 'Mortgage',
 7: 'Other',
 8: 'Personal loan',
 9: 'Student loan'}

In [18]:
# Preview labels
df[["target_grouped", "label"]].drop_duplicates().sort_values("label")

       target_grouped  label
199         Auto loan      0
10       Bank account      1
3         Credit card      2
0    Credit reporting      3
1     Debt collection      4
16     Money transfer      5
42           Mortgage      6
435             Other      7
15      Personal loan      8
161      Student loan      9

### Sample data for stronger transformation training

In [19]:
df_transformer = df[["text_clean", "target_grouped", "label"]].sample(
    n=100000,
    random_state = 42
)

In [20]:
df_transformer.isnull().sum()

text_clean        0
target_grouped    0
label             0
dtype: int64

In [21]:
df_transformer.shape

(100000, 3)

In [22]:
df_transformer["target_grouped"].value_counts()

target_grouped
Credit reporting    66650
Debt collection     11190
Credit card          6109
Bank account         4991
Mortgage             3747
Money transfer       3058
Student loan         1669
Auto loan            1297
Personal loan        1154
Other                 135
Name: count, dtype: int64

### Create Train-Test-Split

In [23]:
# split data in test and train

train_df, test_df = train_test_split(
    df_transformer,
    test_size = 0.2,
    random_state=42,
    stratify=df_transformer["label"]
)

In [24]:
# check shape

print(train_df.shape, test_df.shape)

(80000, 3) (20000, 3)

In [25]:
# check label distribution in train split

train_df["target_grouped"].value_counts()

target_grouped
Credit reporting    53320
Debt collection      8952
Credit card          4887
Bank account         3993
Mortgage             2998
Money transfer       2446
Student loan         1335
Auto loan            1038
Personal loan         923
Other                 108
Name: count, dtype: int64

In [26]:
# check label distribution in test split

test_df["target_grouped"].value_counts()

target_grouped
Credit reporting    13330
Debt collection      2238
Credit card          1222
Bank account          998
Mortgage              749
Money transfer        612
Student loan          334
Auto loan             259
Personal loan         231
Other                  27
Name: count, dtype: int64

### Convert to transformers dataset

In [27]:
# convert train and test dataframes to Hugging Face datasets
train_dataset = Dataset.from_pandas(train_df[["text_clean", "label"]])
test_dataset = Dataset.from_pandas(test_df[["text_clean", "label"]])

In [28]:
# check names

print(train_dataset.column_names)

['text_clean', 'label', '__index_level_0__']

In [29]:
print(test_dataset.column_names)

['text_clean', 'label', '__index_level_0__']

### set the model name

[Model Link](https://huggingface.co/FacebookAI/roberta-base)

In [30]:
# set the stronger transformer backbone
model_name = "roberta-base"

In [31]:
# Load Tokenizer for RoBERTa
tokenizer = AutoTokenizer.from_pretrained(model_name)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

### Tokenize

In [32]:
# create the tokenization function

def tokenize_function(examples):
    return tokenizer(
        examples["text_clean"],
        padding="max_length",
        truncation=True,
        max_length=256
    )

#### Apply tokenizer

In [33]:
# apply tokenization to train and test dataset

train_dataset = train_dataset.map(tokenize_function, batched=True)
test_dataset = test_dataset.map(tokenize_function, batch_size=True)

Map:   0%|          | 0/80000 [00:00<?, ? examples/s]

Map:   0%|          | 0/20000 [00:00<?, ? examples/s]

In [34]:
train_dataset.column_names

['text_clean', 'label', '__index_level_0__', 'input_ids', 'attention_mask']

In [35]:
# Remove extra columns if present
cols_to_remove = [col for col in ["text_clean", "__index_level_0__"] if col in train_dataset.column_names]
train_dataset = train_dataset.remove_columns(cols_to_remove)
test_dataset = test_dataset.remove_columns(cols_to_remove)

In [36]:
# set pytorch format for pytorch
train_dataset.set_format("torch")
test_dataset.set_format("torch")

In [37]:
train_dataset

Dataset({
    features: ['label', 'input_ids', 'attention_mask'],
    num_rows: 80000
})

In [38]:
# check final dataset columns and one sample

print(train_dataset.column_names)
print(train_dataset[0])

['label', 'input_ids', 'attention_mask']
{'label': tensor(2), 'input_ids': tensor([    0,   179,  3023, 46628,     9,   954,   939,   439,     7,    10,
         4044,  1400,     8,   939,  3584,    10,   891,     9,  1964,    13,
           10,  1928,  9310,     5,  1087,    21,    59,   389, 16273,     5,
         1055,   906,  1661,   162,    10,  1361,  1886,   187,   939,    21,
         2159,  3617,  1964,    31,  4044,   939,  1507,     8,  1419,    62,
           13,    24,  3225,   939,   399,   326,   190,  4883,    14,     5,
         4033,    21,   342,    15,     5,    92,  1361,  1886,     8,    45,
           15,     5,    65,    14,   939,  4507,     7,     5,  1055,   906,
           10,   186,    50,    98,   423,   939,   314,     7,  3023, 46628,
           13,  3112,  7196,   147,   939,   794,   127,   284,     8,   127,
           11,  2074,    52,   376,   124,    11,  3023, 46628,    30,    14,
           86,   939,    33,   829,  4044,  4033,    19,   628,  4029,  3207,
           13,    10,   891,     9,   377,     5,  1087,  2140,   439,    31,
           59,   389, 16273,     7,    81,  8963, 16273,   939,  5590,  4044,
            8,   553,   106,     7,   492,  9131,    10,  6720,    25,    42,
           21,   127,    78,  3207,   939,    21,    66,     9,     5,   247,
            8,   939,   269,   770,     7,   304,     5,  1886,    51,    26,
           14,    70,     5,  3154,    32, 23660,     8,  3891,   939,   240,
            7,   582,    24,   939,  1834,    19,  4389,    71,  4389,     8,
           51,   174,   162,     5,   276,   631,  2350,   939,    21,  5590,
          456,    30,   106,     8,    77,   939,  1381,     7,  3922,     5,
         1068,   939,   300,     5,   276,  6784,   456,   939,  2854,     7,
          582,   103,  2861,    53,  3982, 16273,    13,   130,   377,     9,
          628,  3207,    16, 18809,     5,  2861,    16,   292,   498,     5,
         3031,  1087,     2,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     1,     1,     1]), 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])}

### Compute class weights from the training splits

In [39]:
# get sorted label ids from the training data

class_ids = sorted(train_df["label"].unique())

In [40]:
class_ids

[np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 np.int64(7),
 np.int64(8),
 np.int64(9)]

In [41]:
# Compute balanced class weights
class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.array(class_ids),
    y=train_df["label"].values
)

In [42]:
class_weights

array([ 7.70712909,  2.00350614,  1.63699611,  0.15003751,  0.89365505,
        3.27064595,  2.66844563, 74.07407407,  8.66738895,  5.99250936])

In [43]:
# Convert class weights to PyTorch tensor
class_weights_tensor = torch.tensor(class_weights, dtype=torch.float)

In [44]:
class_weights_tensor

tensor([ 7.7071,  2.0035,  1.6370,  0.1500,  0.8937,  3.2706,  2.6684, 74.0741,
         8.6674,  5.9925])

#### Load RoBERTa model

In [45]:
# Load RoBERTa model for classification
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=len(label2id),
    id2label=id2label,
    label2id=label2id
)

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                             | Status     |
--------------------------------+------------+-
lm_head.dense.bias              | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
classifier.out_proj.weight      | MISSING    |
classifier.dense.bias           | MISSING    |
classifier.out_proj.bias        | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

#### Create a weighted Trainer class

In [46]:
# Create a custom Trainer that uses weighted cross-entropy loss
class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.get("labels")
        outputs = model(**inputs)
        logits = outputs.get("logits")

        loss_fct = nn.CrossEntropyLoss(weight=class_weights_tensor.to(model.device))
        loss = loss_fct(logits, labels)

        return (loss, outputs) if return_outputs else loss

#### Create the metric function

In [47]:
# Create metric function for evaluation
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)

    accuracy = accuracy_score(labels, preds)
    weighted_f1 = f1_score(labels, preds, average="weighted", zero_division=0)
    macro_f1 = f1_score(labels, preds, average="macro", zero_division=0)

    return {
        "accuracy": accuracy,
        "weighted_f1": weighted_f1,
        "macro_f1": macro_f1
    }

### Training Arguments and Trainer setup

In [48]:
# Define training arguments
training_args = TrainingArguments(
    output_dir="./roberta_results_250k",
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=2,
    num_train_epochs=3,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="weighted_f1",
    greater_is_better=True,
    save_total_limit=1,
    report_to="none"
)

If memory is tight just use:

- per_device_train_batch_size=2
- per_device_eval_batch_size=2
- gradient_accumulation_steps=4

In [49]:
# Create weighted trainer
trainer = WeightedTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

#### device check

### Sanity check

In [50]:
# Check one batch sample
print(train_dataset[0])

{'label': tensor(2), 'input_ids': tensor([    0,   179,  3023, 46628,     9,   954,   939,   439,     7,    10,
         4044,  1400,     8,   939,  3584,    10,   891,     9,  1964,    13,
           10,  1928,  9310,     5,  1087,    21,    59,   389, 16273,     5,
         1055,   906,  1661,   162,    10,  1361,  1886,   187,   939,    21,
         2159,  3617,  1964,    31,  4044,   939,  1507,     8,  1419,    62,
           13,    24,  3225,   939,   399,   326,   190,  4883,    14,     5,
         4033,    21,   342,    15,     5,    92,  1361,  1886,     8,    45,
           15,     5,    65,    14,   939,  4507,     7,     5,  1055,   906,
           10,   186,    50,    98,   423,   939,   314,     7,  3023, 46628,
           13,  3112,  7196,   147,   939,   794,   127,   284,     8,   127,
           11,  2074,    52,   376,   124,    11,  3023, 46628,    30,    14,
           86,   939,    33,   829,  4044,  4033,    19,   628,  4029,  3207,
           13,    10,   891,     9,   377,     5,  1087,  2140,   439,    31,
           59,   389, 16273,     7,    81,  8963, 16273,   939,  5590,  4044,
            8,   553,   106,     7,   492,  9131,    10,  6720,    25,    42,
           21,   127,    78,  3207,   939,    21,    66,     9,     5,   247,
            8,   939,   269,   770,     7,   304,     5,  1886,    51,    26,
           14,    70,     5,  3154,    32, 23660,     8,  3891,   939,   240,
            7,   582,    24,   939,  1834,    19,  4389,    71,  4389,     8,
           51,   174,   162,     5,   276,   631,  2350,   939,    21,  5590,
          456,    30,   106,     8,    77,   939,  1381,     7,  3922,     5,
         1068,   939,   300,     5,   276,  6784,   456,   939,  2854,     7,
          582,   103,  2861,    53,  3982, 16273,    13,   130,   377,     9,
          628,  3207,    16, 18809,     5,  2861,    16,   292,   498,     5,
         3031,  1087,     2,     1,     1,     1,     1,     1,     1,     1,
            1,     1,     1,     1,     1,     1]), 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])}

In [51]:
# Check model device
print(next(model.parameters()).device)

cuda:0

In [52]:
# Check GPU availability
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0) if torch.cuda.is_available() else "CPU only")

True
Tesla T4

### Train Model

In [53]:
# Train the RoBERTa model

trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.weight', 'roberta.embeddings.LayerNorm.bias', 'roberta.encoder.layer.0.attention.output.LayerNorm.weight', 'roberta.encoder.layer.0.attention.output.LayerNorm.bias', 'roberta.encoder.layer.0.output.LayerNorm.weight', 'roberta.encoder.layer.0.output.LayerNorm.bias', 'roberta.encoder.layer.1.attention.output.LayerNorm.weight', 'roberta.encoder.layer.1.attention.output.LayerNorm.bias', 'roberta.encoder.layer.1.output.LayerNorm.weight', 'roberta.encoder.layer.1.output.LayerNorm.bias', 'roberta.encoder.layer.2.attention.output.LayerNorm.weight', 'roberta.encoder.layer.2.attention.output.LayerNorm.bias', 'roberta.encoder.layer.2.output.LayerNorm.weight', 'roberta.encoder.layer.2.output.LayerNorm.bias', 'roberta.encoder.layer.3.attention.output.LayerNorm.weight', 'roberta.encoder.layer.3.attention.output.LayerNorm.bias', 'roberta.encoder.layer.3.output.LayerNorm.weight', 'roberta.encoder.layer.3.output.LayerNorm.bias', 'roberta.encoder.layer.4.attention.output.LayerNorm.weight', 'roberta.encoder.layer.4.attention.output.LayerNorm.bias', 'roberta.encoder.layer.4.output.LayerNorm.weight', 'roberta.encoder.layer.4.output.LayerNorm.bias', 'roberta.encoder.layer.5.attention.output.LayerNorm.weight', 'roberta.encoder.layer.5.attention.output.LayerNorm.bias', 'roberta.encoder.layer.5.output.LayerNorm.weight', 'roberta.encoder.layer.5.output.LayerNorm.bias', 'roberta.encoder.layer.6.attention.output.LayerNorm.weight', 'roberta.encoder.layer.6.attention.output.LayerNorm.bias', 'roberta.encoder.layer.6.output.LayerNorm.weight', 'roberta.encoder.layer.6.output.LayerNorm.bias', 'roberta.encoder.layer.7.attention.output.LayerNorm.weight', 'roberta.encoder.layer.7.attention.output.LayerNorm.bias', 'roberta.encoder.layer.7.output.LayerNorm.weight', 'roberta.encoder.layer.7.output.LayerNorm.bias', 'roberta.encoder.layer.8.attention.output.LayerNorm.weight', 'roberta.encoder.layer.8.attention.output.LayerNorm.bias', 'roberta.encoder.layer.8.output.LayerNorm.weight', 'roberta.encoder.layer.8.output.LayerNorm.bias', 'roberta.encoder.layer.9.attention.output.LayerNorm.weight', 'roberta.encoder.layer.9.attention.output.LayerNorm.bias', 'roberta.encoder.layer.9.output.LayerNorm.weight', 'roberta.encoder.layer.9.output.LayerNorm.bias', 'roberta.encoder.layer.10.attention.output.LayerNorm.weight', 'roberta.encoder.layer.10.attention.output.LayerNorm.bias', 'roberta.encoder.layer.10.output.LayerNorm.weight', 'roberta.encoder.layer.10.output.LayerNorm.bias', 'roberta.encoder.layer.11.attention.output.LayerNorm.weight', 'roberta.encoder.layer.11.attention.output.LayerNorm.bias', 'roberta.encoder.layer.11.output.LayerNorm.weight', 'roberta.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.beta', 'roberta.embeddings.LayerNorm.gamma', 'roberta.encoder.layer.0.attention.output.LayerNorm.beta', 'roberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.0.output.LayerNorm.beta', 'roberta.encoder.layer.0.output.LayerNorm.gamma', 'roberta.encoder.layer.1.attention.output.LayerNorm.beta', 'roberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.1.output.LayerNorm.beta', 'roberta.encoder.layer.1.output.LayerNorm.gamma', 'roberta.encoder.layer.2.attention.output.LayerNorm.beta', 'roberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.2.output.LayerNorm.beta', 'roberta.encoder.layer.2.output.LayerNorm.gamma', 'roberta.encoder.layer.3.attention.output.LayerNorm.beta', 'roberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.3.output.LayerNorm.beta', 'roberta.encoder.layer.3.output.LayerNorm.gamma', 'roberta.encoder.layer.4.attention.output.LayerNorm.beta', 'roberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.4.output.LayerNorm.beta', 'roberta.encoder.layer.4.output.LayerNorm.gamma', 'roberta.encoder.layer.5.attention.output.LayerNorm.beta', 'roberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.5.output.LayerNorm.beta', 'roberta.encoder.layer.5.output.LayerNorm.gamma', 'roberta.encoder.layer.6.attention.output.LayerNorm.beta', 'roberta.encoder.layer.6.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.6.output.LayerNorm.beta', 'roberta.encoder.layer.6.output.LayerNorm.gamma', 'roberta.encoder.layer.7.attention.output.LayerNorm.beta', 'roberta.encoder.layer.7.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.7.output.LayerNorm.beta', 'roberta.encoder.layer.7.output.LayerNorm.gamma', 'roberta.encoder.layer.8.attention.output.LayerNorm.beta', 'roberta.encoder.layer.8.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.8.output.LayerNorm.beta', 'roberta.encoder.layer.8.output.LayerNorm.gamma', 'roberta.encoder.layer.9.attention.output.LayerNorm.beta', 'roberta.encoder.layer.9.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.9.output.LayerNorm.beta', 'roberta.encoder.layer.9.output.LayerNorm.gamma', 'roberta.encoder.layer.10.attention.output.LayerNorm.beta', 'roberta.encoder.layer.10.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.10.output.LayerNorm.beta', 'roberta.encoder.layer.10.output.LayerNorm.gamma', 'roberta.encoder.layer.11.attention.output.LayerNorm.beta', 'roberta.encoder.layer.11.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.11.output.LayerNorm.beta', 'roberta.encoder.layer.11.output.LayerNorm.gamma'].

TrainOutput(global_step=30000, training_loss=1.4126724609375, metrics={'train_runtime': 13257.7151, 'train_samples_per_second': 18.103, 'train_steps_per_second': 2.263, 'total_flos': 3.157559451648e+16, 'train_loss': 1.4126724609375, 'epoch': 3.0})

### Predictions

In [54]:
# Generate predictions on the test dataset
predictions = trainer.predict(test_dataset)

In [55]:
# Convert logits to predicted class ids
y_pred_roberta = np.argmax(predictions.predictions, axis=1)

In [56]:
# Extract true labels
y_true_roberta = predictions.label_ids

In [57]:
# Convert numeric ids back to label names
y_pred_roberta_labels = [id2label[i] for i in y_pred_roberta]
y_true_roberta_labels = [id2label[i] for i in y_true_roberta]

In [58]:
# Print classification report
print(classification_report(y_true_roberta_labels, y_pred_roberta_labels, zero_division=0))

                  precision    recall  f1-score   support

       Auto loan       0.62      0.67      0.65       259
    Bank account       0.80      0.85      0.83       998
     Credit card       0.80      0.77      0.79      1222
Credit reporting       0.95      0.95      0.95     13330
 Debt collection       0.78      0.77      0.77      2238
  Money transfer       0.84      0.80      0.82       612
        Mortgage       0.88      0.89      0.88       749
           Other       0.00      0.00      0.00        27
   Personal loan       0.56      0.45      0.50       231
    Student loan       0.82      0.85      0.83       334

        accuracy                           0.90     20000
       macro avg       0.70      0.70      0.70     20000
    weighted avg       0.89      0.90      0.89     20000

In [59]:
# Calculate summary metrics
roberta_accuracy = accuracy_score(y_true_roberta_labels, y_pred_roberta_labels)
roberta_weighted_f1 = f1_score(y_true_roberta_labels, y_pred_roberta_labels, average="weighted", zero_division=0)
roberta_macro_f1 = f1_score(y_true_roberta_labels, y_pred_roberta_labels, average="macro", zero_division=0)

print("RoBERTa Accuracy:", roberta_accuracy)
print("RoBERTa Weighted F1:", roberta_weighted_f1)
print("RoBERTa Macro F1:", roberta_macro_f1)

RoBERTa Accuracy: 0.89585
RoBERTa Weighted F1: 0.8946863570864511
RoBERTa Macro F1: 0.701417950158268

# Save the fine-tuned RoBERTa model and tokenizer
trainer.save_model("models/roberta_complaint_classifier")
tokenizer.save_pretrained("models/roberta_complaint_classifier")

In [60]:
# Example save path in Drive
save_path = "/content/drive/MyDrive/roberta_complaint_classifier"
trainer.save_model(save_path)
tokenizer.save_pretrained(save_path)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('/content/drive/MyDrive/roberta_complaint_classifier/tokenizer_config.json',
 '/content/drive/MyDrive/roberta_complaint_classifier/tokenizer.json')